/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void testAppReturnHelloWorld() {
        App classUnderTest = new App();
        String expected = "Hello World!";
        assertEquals(expected, classUnderTest.getGreeting(), "app should return 'Hello World!'");
    }
}
